### ISSUE TITLE
S3D weights pretrained on Kinetics400 download link cannot be opened

### ISSUE THREAD

**Issue by HangFang6** [Chuhanxx/Temporal_Query_Networks#3]
Very wonderful work！ But when I download S3D weights pretrained on Kinetics400, I can't open the link. Hope the author can update the link, or send a copy to my email. I would be grateful if I could receive a reply.

**Comment by Chuhanxx** [comment]
Hi, 
The download link works from my side.
you can check your firewall setting and retry, or download it from Google Drive: https://drive.google.com/file/d/1BIFysEpnbpCW7Q88gq9zc958N5CMSRmB/view?usp=sharing

**Comment by HangFang6** [comment]
This link works. Thanks for your reply！
