### ISSUE TITLE
How to prepare the datasets?

### ISSUE THREAD

**Issue by Michael-Ray-Sirius** [Chuhanxx/Temporal_Query_Networks#4]
Hi, thanks for your work! 

I feel confused about the dataset preparation, like Diving48 should I extract frames from each mp4?

**Comment by Chuhanxx** [comment]
Hi, 

yes, the dataloader in this repo reads RGB images as input so frames have to be pre-extracted from videos. 
You can use code block like this for frame extraction. 
```
import cv2
vidcap = cv2.VideoCapture(video_path)
success,image = vidcap.read()
count = 0
while success:
  cv2.imwrite("frame%d.jpg" % count, image)     # save frame as JPEG file      
  success,image = vidcap.read()
  print('Read a new frame: ', success)
  count += 1  
```
